### ISSUE TITLE
Circular Reference causes schema not to compile

### ISSUE THREAD

**Issue by ryuuji3** [indigotech/graphql-schema-decorator#65]
Possibly related to Issue #64 

I have two types that refer to each other;
```
@ObjectType({ description: 'Store' })
class StoreType {
  @Field({ type: EmployeeType, isList: true })
  employees: EmployeeType[]
}

@ObjectType({ description: 'Employee' })
class EmployeeType {
  @Field({ type: StoreType })
  store: StoreType
}
```

As a result, I got this when trying to start the server;

```
{ Error: @ObjectType()'s store is annotated by @Field() but no type could be inferred
    at SchemaFactoryError (/Users/ryuuji3/Projects/shift-scheduler/node_modules/graphql-schema-decorator/src/type-factory/schema.type-factory.ts:27:5)
    at fieldMetadataList.reduce (/Users/ryuuji3/Projects/shift-scheduler/node_modules/graphql-schema-decorator/src/type-factory/object.type-factory.ts:52:21)
    at Array.reduce (native)
    at metadata_builder_1.getMetadataBuilder.buildObjectTypeMetadata.map.metadata (/Users/ryuuji3/Projects/shift-scheduler/node_modules/graphql-schema-decorator/src/type-factory/object.type-factory.ts:49:44)
    at Array.map (native)
    at Object.objectTypeFactory (/Users/ryuuji3/Projects/shift-scheduler/node_modules/graphql-schema-decorator/src/type-factory/object.type-factory.ts:22:8)
    at convertType (/Users/ryuuji3/Projects/shift-scheduler/node_modules/graphql-schema-decorator/src/type-factory/field.type-factory.ts:53:20)
    at Object.fieldTypeFactory (/Users/ryuuji3/Projects/shift-scheduler/node_modules/graphql-schema-decorator/src/type-factory/field.type-factory.ts:217:21)
    at fieldMetadataList.reduce (/Users/ryuuji3/Projects/shift-scheduler/node_modules/graphql-schema-decorator/src/type-factory/object.type-factory.ts:50:25)
    at Array.reduce (native) type: 2 }
```

When commenting out `Store.employees`, it compiles successfully. Then I uncommented `Store.employees` and commented out `Employee.store` and it compiled successfully.

Thank you!

**Comment by felipesabino** [comment]
@ryuuji3 

Yap, circular references are still not being properly handled, sorry about that.

Also, it is definitely related to #64.

I will this open so that we can tackle after [1.0](https://github.com/indigotech/graphql-schema-decorator/milestone/1) is released.

**Comment by felipesabino** [comment]
@ryuuji3 Oh, meanwhile please feel free to send us a PR with a fix suggestion 😉

**Comment by ryuuji3** [comment]
Thank you for your hard work!

I'm not confident in my abilities to make any fixes but I'll look into it :p

Thanks again

**Comment by pie6k** [comment]
I believe, that in order to solve this, it'd need to change API so instead of using eg.

```
@Field({type: GraphQLID, nonNull: true})
```

You'd have to use getter:

```
@Field({type: () => GraphQLID, nonNull: true})
```

Such getter does not require to have all definitions instantly, and therefore solves issue.

If that's true, it should be relatively easy to implement it.

I'd be happy to create PR, but it'd be very helpful to have some guide as I'm not quite familiar with this repo.

**Comment by pie6k** [comment]
Also, there is another fork that seems to have it solved:

https://github.com/Cactucs/graphql-schema-decorator/commit/6ace1fb78883362ecfab87070a7a38c8b232daea

**Comment by pie6k** [comment]
I've created PR:

https://github.com/indigotech/graphql-schema-decorator/pull/72

**Comment by pie6k** [comment]
Since there was no reaction to PR I've created, I thought this repo is not really active.

 I've created my own library allowing creating schema with decorators - https://github.com/prismake/typegql

**Comment by MichalLytek** [comment]
@pie6k Maybe instead of writing yet another TypeScript-GraphQL-decorators library, let's join our forces and make one great lib full of features 😉 
You can take a look at [TypeGraphQL](https://github.com/19majkel94/type-graphql) 😜
